ELEVENLABS_STT_MODELS = ("scribe_v2_realtime",)

ELEVENLABS_STT_LANGUAGES = (
    "auto",
    "af",
    "am",
    "ar",
    "as",
    "az",
    "be",
    "bg",
    "bn",
    "bs",
    "ca",
    "ceb",
    "cs",
    "cy",
    "da",
    "de",
    "el",
    "en",
    "es",
    "et",
    "fa",
    "fi",
    "fil",
    "fr",
    "ga",
    "gl",
    "gu",
    "ha",
    "he",
    "hi",
    "hr",
    "hu",
    "hy",
    "id",
    "ig",
    "is",
    "it",
    "ja",
    "jv",
    "ka",
    "kk",
    "km",
    "kn",
    "ko",
    "ku",
    "ky",
    "lo",
    "lt",
    "lv",
    "mi",
    "mk",
    "ml",
    "mn",
    "mr",
    "ms",
    "mt",
    "my",
    "ne",
    "nl",
    "no",
    "ny",
    "oc",
    "or",
    "pa",
    "pl",
    "ps",
    "pt",
    "ro",
    "ru",
    "sd",
    "sk",
    "sl",
    "sn",
    "so",
    "sr",
    "sv",
    "sw",
    "ta",
    "te",
    "tg",
    "th",
    "tr",
    "uk",
    "ur",
    "uz",
    "vi",
    "wo",
    "xh",
    "yue",
    "zh",
    "zu",
)

#: ElevenLabs' premade voices, by their public ids. The same six the template
#: gallery plays, so the voice somebody pressed play on is the voice their
#: agent answers in. Premade ids are shared across every ElevenLabs account,
#: which is what makes a managed list possible for a vendor whose *cloned*
#: voices are per account and cannot be listed here.
#:
#: ``(voice_id, name, gender)``.
ELEVENLABS_PREMADE_VOICES: tuple[tuple[str, str, str], ...] = (
    ("21m00Tcm4TlvDq8ikWAM", "Rachel", "female"),
    ("EXAVITQu4vr4xnSDxMaL", "Bella", "female"),
    ("MF3mGyEYCl7XYWbV9V6O", "Elli", "female"),
    ("pNInz6obpgDQGcFmaJgB", "Adam", "male"),
    ("ErXwobaYiN019PkySvjV", "Antoni", "male"),
    ("TxGEqnHWrfWFTfGW9XjX", "Josh", "male"),
)
