"""organization provider credentials byok vault

Revision ID: 1809fdeebdc6
Revises: d53acd5a9899
Create Date: 2026-08-04 19:14:27.637606

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1809fdeebdc6"
down_revision: Union[str, None] = "d53acd5a9899"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_provider_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("component", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("encrypted_key", sa.Text(), nullable=False),
        sa.Column("key_last_four", sa.String(length=8), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("set_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["set_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "component",
            "provider",
            name="uq_organization_provider_credential",
        ),
    )
    # No separate lookup index. The unique constraint above is already a btree
    # on (organization_id, component, provider) in that order, which is the
    # order every read in organization_credentials.py filters by — a second
    # index on the same tuple would answer no query the first one cannot, and
    # would be maintained on every key rotation for nothing.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("organization_provider_credentials")
    # ### end Alembic commands ###
