"""add processing state in queued runs

Revision ID: 34c8537dfde5
Revises: 02ffd7f23d1d
Create Date: 2026-01-30 14:40:29.905325

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "34c8537dfde5"
down_revision: Union[str, None] = "02ffd7f23d1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: ``sync_enum_values`` cannot add a value in place. It renames
#: ``queued_run_state`` to ``queued_run_state_old``, creates a fresh type with
#: the new value list, casts the column across, then drops the old type. That
#: last step fails while anything still depends on the old type's operators —
#: and ``idx_queued_runs_campaign_state_optimized``, created back in
#: ``fec0fb9a8db7``, is a *partial* index whose ``WHERE state = 'queued'``
#: predicate is exactly such a dependency:
#:
#:     DependentObjectsStillExistError: cannot drop operator
#:     =(queued_run_state,queued_run_state_old) because index
#:     idx_queued_runs_campaign_state_optimized depends on it
#:
#: Production never hit this because the index was missing there — that drift is
#: what ``c8f31a604be7`` was written to close — so the failure only shows up
#: replaying from base: a fresh database, a new deployment, CI. It stopped at 24
#: of ~80 tables.
#:
#: So the index comes out before the swap and goes back after it. ``IF EXISTS``
#: and ``IF NOT EXISTS`` because both states are real: a database replaying
#: migrations in order has the index here, the drifted production one did not.
_DEPENDENT_INDEX = "idx_queued_runs_campaign_state_optimized"
_DEPENDENT_INDEX_DDL = (
    f"CREATE INDEX IF NOT EXISTS {_DEPENDENT_INDEX} "
    "ON queued_runs (campaign_id, state) WHERE state = 'queued'"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.create_index("ix_api_keys_key_hash", "api_keys", ["key_hash"], unique=False)
    op.execute(f"DROP INDEX IF EXISTS {_DEPENDENT_INDEX}")
    op.sync_enum_values(
        enum_schema="public",
        enum_name="queued_run_state",
        new_values=["queued", "processed", "processing", "failed"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="queued_runs", column_name="state"
            )
        ],
        enum_values_to_rename=[],
    )
    op.execute(_DEPENDENT_INDEX_DDL)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Same dependency, same order — removing a value needs the swap too.
    op.execute(f"DROP INDEX IF EXISTS {_DEPENDENT_INDEX}")
    op.sync_enum_values(
        enum_schema="public",
        enum_name="queued_run_state",
        new_values=["queued", "processed", "failed"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="queued_runs", column_name="state"
            )
        ],
        enum_values_to_rename=[],
    )
    op.execute(_DEPENDENT_INDEX_DDL)
    op.drop_index("ix_api_keys_key_hash", table_name="api_keys")
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    # ### end Alembic commands ###
