"""google calendar connections

Revision ID: 6f3a9d1c4e2b
Revises: 1809fdeebdc6
Create Date: 2026-08-08 21:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f3a9d1c4e2b"
down_revision: Union[str, None] = "1809fdeebdc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "google_calendar_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=False),
        sa.Column("encrypted_access_token", sa.Text(), nullable=True),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connected_email", sa.String(length=320), nullable=True),
        sa.Column(
            "calendar_id",
            sa.String(length=255),
            nullable=False,
            server_default="primary",
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("connected_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["connected_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        # One connection per organization, deliberately: see the model
        # docstring. A second `Connect` replaces this row rather than adding
        # one, and this constraint is what set_connection's upsert relies on.
        sa.UniqueConstraint(
            "organization_id", name="uq_google_calendar_connection_org"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("google_calendar_connections")
    # ### end Alembic commands ###
