"""add billing rate config, per-call costing and rollup tables

Adds the Decibyl billing schema:

* ``organization_rate_history`` / ``platform_volume_tiers`` / ``provider_rates``
  — effective-dated rate configuration. Rates are never updated in place, so
  recomputing an old invoice reproduces the original number.
* ``call_cost_items`` — itemised per-call receipt lines. Provider cost and the
  platform fee are separate rows and separate columns, never summed into a
  single stored number.
* ``call_turn_metrics`` — per-turn latency instrumentation.
* ``credit_ledger`` — append-only credit movements.
* ``daily_organization_rollup`` — pre-aggregated dashboard figures, bucketed by
  IST calendar day.
* ``billing_audit_log`` — who changed a rate or moved credit, and from what.

Plus billing columns on ``organizations`` and the per-call cost snapshot on
``workflow_runs``.

Note: autogenerate also detected two pre-existing model/database drifts that
predate this change and are identical on main — a missing
``idx_queued_runs_campaign_state_optimized`` index and an extra
``workflow_definitions.call_disposition_codes`` column. Both were removed from
this migration: they are unrelated to billing, and the column drop would have
destroyed data.

Revision ID: 810aaefd657d
Revises: 00b0201ad918
Create Date: 2026-07-29 12:14:01.031402

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "810aaefd657d"
down_revision: Union[str, None] = "00b0201ad918"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_volume_tiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("min_period_minutes", sa.Integer(), nullable=False),
        sa.Column("platform_rate_mpaise", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_platform_volume_tiers_effective",
        "platform_volume_tiers",
        ["effective_from", "effective_to"],
        unique=False,
    )
    op.create_table(
        "provider_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("component", sa.String(length=16), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("rate_mpaise", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_provider_rates_lookup",
        "provider_rates",
        ["provider", "component", "effective_from"],
        unique=False,
    )
    op.create_index(
        "uq_provider_rates_open",
        "provider_rates",
        ["provider", "component"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.create_table(
        "daily_organization_rollup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("calls", sa.Integer(), nullable=False),
        sa.Column("answered_calls", sa.Integer(), nullable=False),
        sa.Column("completed_calls", sa.Integer(), nullable=False),
        sa.Column("billable_seconds", sa.BigInteger(), nullable=False),
        sa.Column("billable_minutes", sa.BigInteger(), nullable=False),
        sa.Column("provider_cost_paise", sa.BigInteger(), nullable=False),
        sa.Column("charged_paise", sa.BigInteger(), nullable=False),
        sa.Column("margin_paise", sa.BigInteger(), nullable=False),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "day", name="uq_daily_rollup_org_day"),
    )
    op.create_index(
        "ix_daily_rollup_day", "daily_organization_rollup", ["day"], unique=False
    )
    op.create_index(
        "ix_daily_rollup_org_day",
        "daily_organization_rollup",
        ["organization_id", "day"],
        unique=False,
    )
    op.create_table(
        "billing_audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("old_value", sa.JSON(), nullable=False),
        sa.Column("new_value", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_billing_audit_action", "billing_audit_log", ["action"], unique=False
    )
    op.create_index(
        "ix_billing_audit_org_created",
        "billing_audit_log",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "credit_ledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("delta_paise", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("ref_type", sa.String(length=32), nullable=True),
        sa.Column("ref_id", sa.String(length=64), nullable=True),
        sa.Column("balance_after_paise", sa.BigInteger(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_credit_ledger_org_created",
        "credit_ledger",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_credit_ledger_usage_ref",
        "credit_ledger",
        ["organization_id", "ref_type", "ref_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'usage' AND ref_id IS NOT NULL"),
    )
    op.create_table(
        "organization_rate_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("platform_rate_mpaise", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("set_by", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["set_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_org_rate_history_org_effective",
        "organization_rate_history",
        ["organization_id", "effective_from"],
        unique=False,
    )
    op.create_index(
        "uq_org_rate_history_open",
        "organization_rate_history",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.create_table(
        "call_cost_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=False),
        sa.Column("component", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("units", sa.BigInteger(), nullable=False),
        sa.Column("unit_rate_mpaise", sa.Integer(), nullable=False),
        sa.Column("cost_paise", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_call_cost_items_component", "call_cost_items", ["component"], unique=False
    )
    op.create_index(
        "ix_call_cost_items_run", "call_cost_items", ["workflow_run_id"], unique=False
    )
    op.create_table(
        "call_turn_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column("t_user_stopped_ms", sa.Integer(), nullable=True),
        sa.Column("t_endpoint_fired_ms", sa.Integer(), nullable=True),
        sa.Column("t_stt_final_ms", sa.Integer(), nullable=True),
        sa.Column("t_llm_first_token_ms", sa.Integer(), nullable=True),
        sa.Column("t_tts_first_byte_ms", sa.Integer(), nullable=True),
        sa.Column("t_audio_out_ms", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("tool_called", sa.String(length=128), nullable=True),
        sa.Column("tool_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_run_id", "turn_index", name="uq_call_turn_metrics_run_turn"
        ),
    )
    op.create_index(
        "ix_call_turn_metrics_latency",
        "call_turn_metrics",
        ["created_at", "latency_ms"],
        unique=False,
    )
    op.create_index(
        "ix_call_turn_metrics_run",
        "call_turn_metrics",
        ["workflow_run_id"],
        unique=False,
    )
    op.add_column(
        "organizations", sa.Column("platform_rate_mpaise", sa.Integer(), nullable=True)
    )
    op.add_column(
        "organizations",
        sa.Column(
            "billing_currency",
            sa.String(length=3),
            server_default=sa.text("'INR'"),
            nullable=False,
        ),
    )
    op.add_column(
        "organizations", sa.Column("account_type", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "organizations", sa.Column("billing_name", sa.String(), nullable=True)
    )
    op.add_column(
        "organizations",
        sa.Column(
            "billing_status",
            sa.String(length=16),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
    )
    op.add_column(
        "workflow_runs",
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "workflow_runs",
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "workflow_runs", sa.Column("language", sa.String(length=16), nullable=True)
    )
    op.add_column(
        "workflow_runs", sa.Column("billable_seconds", sa.Integer(), nullable=True)
    )
    op.add_column(
        "workflow_runs",
        sa.Column("platform_rate_mpaise_applied", sa.Integer(), nullable=True),
    )
    op.add_column(
        "workflow_runs",
        sa.Column("total_provider_cost_paise", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "workflow_runs",
        sa.Column("total_charged_paise", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "workflow_runs",
        sa.Column("costed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "idx_workflow_runs_created_at", "workflow_runs", ["created_at"], unique=False
    )
    op.create_index(
        "idx_workflow_runs_workflow_created_at",
        "workflow_runs",
        ["workflow_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_workflow_runs_workflow_created_at", table_name="workflow_runs")
    op.drop_index("idx_workflow_runs_created_at", table_name="workflow_runs")
    op.drop_column("workflow_runs", "costed_at")
    op.drop_column("workflow_runs", "total_charged_paise")
    op.drop_column("workflow_runs", "total_provider_cost_paise")
    op.drop_column("workflow_runs", "platform_rate_mpaise_applied")
    op.drop_column("workflow_runs", "billable_seconds")
    op.drop_column("workflow_runs", "language")
    op.drop_column("workflow_runs", "ended_at")
    op.drop_column("workflow_runs", "answered_at")
    op.drop_column("organizations", "billing_status")
    op.drop_column("organizations", "billing_name")
    op.drop_column("organizations", "account_type")
    op.drop_column("organizations", "billing_currency")
    op.drop_column("organizations", "platform_rate_mpaise")
    op.drop_index("ix_call_turn_metrics_run", table_name="call_turn_metrics")
    op.drop_index("ix_call_turn_metrics_latency", table_name="call_turn_metrics")
    op.drop_table("call_turn_metrics")
    op.drop_index("ix_call_cost_items_run", table_name="call_cost_items")
    op.drop_index("ix_call_cost_items_component", table_name="call_cost_items")
    op.drop_table("call_cost_items")
    op.drop_index(
        "uq_org_rate_history_open",
        table_name="organization_rate_history",
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.drop_index(
        "ix_org_rate_history_org_effective", table_name="organization_rate_history"
    )
    op.drop_table("organization_rate_history")
    op.drop_index(
        "uq_credit_ledger_usage_ref",
        table_name="credit_ledger",
        postgresql_where=sa.text("kind = 'usage' AND ref_id IS NOT NULL"),
    )
    op.drop_index("ix_credit_ledger_org_created", table_name="credit_ledger")
    op.drop_table("credit_ledger")
    op.drop_index("ix_billing_audit_org_created", table_name="billing_audit_log")
    op.drop_index("ix_billing_audit_action", table_name="billing_audit_log")
    op.drop_table("billing_audit_log")
    op.drop_index("ix_daily_rollup_org_day", table_name="daily_organization_rollup")
    op.drop_index("ix_daily_rollup_day", table_name="daily_organization_rollup")
    op.drop_table("daily_organization_rollup")
    op.drop_index(
        "uq_provider_rates_open",
        table_name="provider_rates",
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.drop_index("ix_provider_rates_lookup", table_name="provider_rates")
    op.drop_table("provider_rates")
    op.drop_index(
        "ix_platform_volume_tiers_effective", table_name="platform_volume_tiers"
    )
    op.drop_table("platform_volume_tiers")
    # ### end Alembic commands ###
