"""user mfa columns

Revision ID: 898f64af267f
Revises: a7d15e93b2c4
Create Date: 2026-07-31 14:30:11.196030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898f64af267f'
down_revision: Union[str, None] = 'a7d15e93b2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_secret_encrypted', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('mfa_last_counter', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('mfa_recovery_hashes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_recovery_hashes')
    op.drop_column('users', 'mfa_last_counter')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret_encrypted')
    # ### end Alembic commands ###
