/**
 * PostHog event names — frontend events only.
 */
export const PostHogEvent = {
  WORKFLOW_EDITOR_OPENED: "workflow_editor_opened",
  WORKFLOW_NODE_ADDED: "workflow_node_added",
  WORKFLOW_RUN_DETAILS_VIEWED: "workflow_run_details_viewed",
  RECORDING_PLAYED: "recording_played",
  TRANSCRIPT_VIEWED: "transcript_viewed",
  WEB_CALL_INITIATED: "web_call_initiated",
  SIGNED_IN: "signed_in",
  SLACK_COMMUNITY_CLICKED: "slack_community_clicked",
  HIRE_EXPERT_OPENED: "hire_expert_opened",
  HIRE_EXPERT_SUBMITTED: "hire_expert_submitted",
  BUY_CREDITS_CLICKED: "buy_credits_clicked",
  BUY_CREDITS_AMOUNT_SELECTED: "buy_credits_amount_selected",
  CUSTOM_PRICING_CLICKED: "custom_pricing_clicked",
  ENTERPRISE_LEAD_OPENED: "enterprise_lead_opened",
  ENTERPRISE_LEAD_SUBMITTED: "enterprise_lead_submitted",
  HIRE_NUDGE_SHOWN: "hire_nudge_shown",
  HIRE_NUDGE_CLICKED: "hire_nudge_clicked",
  HIRE_NUDGE_DISMISSED: "hire_nudge_dismissed",
  HIRE_NUDGE_EXPIRED: "hire_nudge_expired",
  ONBOARDING_SHOWN: "onboarding_shown",
  ONBOARDING_SUBMITTED: "onboarding_submitted",
  ONBOARDING_SKIPPED: "onboarding_skipped",
  // Sign-up form, before there is a user to identify.
  SIGNUP_SUBMITTED: "signup_submitted",
  SIGNUP_SUCCEEDED: "signup_succeeded",
  SIGNUP_FAILED: "signup_failed",
  // The first-agent journey (/start): template → name → hear it → done.
  // One event per decision, so the funnel shows where people stop.
  FIRST_AGENT_STARTED: "first_agent_started",
  FIRST_AGENT_TEMPLATE_PICKED: "first_agent_template_picked",
  FIRST_AGENT_VOICE_PICKED: "first_agent_voice_picked",
  FIRST_AGENT_SCRATCH_CHOSEN: "first_agent_scratch_chosen",
  FIRST_AGENT_STEP_BACK: "first_agent_step_back",
  FIRST_AGENT_CREATED: "first_agent_created",
  FIRST_AGENT_CREATE_FAILED: "first_agent_create_failed",
  FIRST_AGENT_TEST_STARTED: "first_agent_test_started",
  FIRST_AGENT_TEST_COMPLETED: "first_agent_test_completed",
  FIRST_AGENT_TEST_FAILED: "first_agent_test_failed",
  FIRST_AGENT_VERIFY_NUMBER_CLICKED: "first_agent_verify_number_clicked",
  FIRST_AGENT_HELP_CLICKED: "first_agent_help_clicked",
  FIRST_AGENT_FINISHED: "first_agent_finished",
} as const;
