#!/usr/bin/env bash
set -e

###############################################################################
### WHAT THIS CONTAINER IS
###############################################################################
#
# Four different services live in this one process tree, and three of them are
# singletons that nothing enforces:
#
#   alembic upgrade head    once, at boot          schema migration
#   ari_manager             exactly 1              Asterisk event listener
#   campaign_orchestrator   exactly 1              batch scheduling and retries
#   uvicorn                 FASTAPI_WORKERS        HTTP *and every live call*
#   arq                     ARQ_WORKERS            post-call costing, reports
#
# Until this script had a role, running the same container on a second machine
# ran a second orchestrator and a second ARI manager. Neither errors. The
# orchestrator dedupes with an in-memory dict and subscribes to a Redis pub/sub
# channel, which fans out to every subscriber -- so N nodes means N copies of
# every batch event and N times the dial attempts, and the first evidence is
# the carrier bill. The ARI manager is the same shape with inbound calls. And
# three nodes booting together run three concurrent migrations.
#
# So the machine cannot be scaled out by adding nodes. DECIBYL_ROLE is what
# makes it possible:
#
#   all      (default)  everything, exactly as before. One box.
#   media               uvicorn ONLY. No migration, no singletons, no arq.
#                       Safe to run on as many machines as you like.
#   control             migration, singletons and arq. Exactly one machine.
#
# A two-machine deployment is one `control` and one or more `media`. Bring
# control up FIRST so the schema is at head before any media node serves a
# request against it.
#
# NOTE FOR WHOEVER SPLITS THE NODES: nginx's upstream list is generated by
# setup_remote.sh from FASTAPI_WORKERS and points at LOCAL ports. It balances
# processes, never machines. A `control` node runs no uvicorn at all, so
# nothing should route HTTP to it -- put the load balancer in front of the
# media nodes only.
#
###############################################################################
### THE SHARED FATE THAT REMAINS, AND WHY IT IS NOT FIXED HERE
###############################################################################
#
# `wait -n` at the bottom tears the container down when ANY child exits, so
# docker restarts the lot. On DECIBYL_ROLE=all that means a crash in post-call
# costing kills every conversation in flight -- a billing bug drops live calls.
#
# Splitting the roles is what actually fixes it: on separate containers, an arq
# crash restarts the control container and the media container never notices.
# Changing the teardown rule instead would leave a container running with a
# dead worker and nginx still routing to its port, which is worse and quieter.
#
###############################################################################
### CONFIGURATION
###############################################################################

BASE_DIR="$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")" && pwd)"
ENV_FILE="$BASE_DIR/api/.env"

ARQ_WORKERS=${ARQ_WORKERS:-1}
FASTAPI_WORKERS=${FASTAPI_WORKERS:-1}
UVICORN_BASE_PORT=${UVICORN_BASE_PORT:-8000}

# Defaults to "all", so an existing deployment that sets nothing behaves
# exactly as it did before this variable existed.
DECIBYL_ROLE=${DECIBYL_ROLE:-all}

# Set by the test that asserts what each role starts. Prints the plan and
# exits without launching anything or touching the database.
PRINT_PLAN=${DECIBYL_PRINT_PLAN:-0}

case "$DECIBYL_ROLE" in
  all|media|control) ;;
  *)
    # Refused rather than defaulted. A typo silently falling back to "all"
    # would start a second orchestrator on a node meant to be media-only,
    # which is the exact failure the role exists to prevent and the one that
    # produces no error of its own.
    echo "DECIBYL_ROLE='$DECIBYL_ROLE' is not one of: all, media, control" >&2
    exit 1
    ;;
esac

# Which roles run what. Named as predicates so each start site reads as the
# reason it is there rather than as a string comparison.
runs_migrations=0;  [[ "$DECIBYL_ROLE" != media ]] && runs_migrations=1
runs_singletons=0;  [[ "$DECIBYL_ROLE" != media ]] && runs_singletons=1
runs_arq=0;         [[ "$DECIBYL_ROLE" != media ]] && runs_arq=1
runs_uvicorn=0;     [[ "$DECIBYL_ROLE" != control ]] && runs_uvicorn=1

cd "$BASE_DIR"
echo "Starting Decibyl Services (DOCKER, role=$DECIBYL_ROLE) at $(date) in BASE_DIR: ${BASE_DIR}"

###############################################################################
### 1) Load env file if mounted (env normally comes from docker-compose)
###############################################################################

if [[ -f "$ENV_FILE" ]]; then
  set -a && . "$ENV_FILE" && set +a
fi

###############################################################################
### 2) Run migrations
###############################################################################
#
# Skipped entirely on a media node. Three nodes booting together otherwise run
# three concurrent migrations against one database, and the losers fail in ways
# that read like a broken migration rather than a race.

if (( runs_migrations )) && (( ! PRINT_PLAN )); then
  alembic -c "$BASE_DIR/api/alembic.ini" upgrade head
elif (( runs_migrations )); then
  echo "PLAN migrations"
else
  echo "role=media: skipping migrations (the control node owns the schema)"
fi

###############################################################################
### 3) Signal handling — forward TERM/INT to children for clean docker stop
###############################################################################

pids=()

shutdown() {
  echo "Received shutdown signal, stopping services..."
  for pid in "${pids[@]}"; do
    kill -TERM "$pid" 2>/dev/null || true
  done
  wait
  exit 0
}

trap shutdown TERM INT

start() {
  local name=$1
  shift
  if (( PRINT_PLAN )); then
    # Printing rather than starting, so the role wiring can be asserted in a
    # test. Without this the only way to find out what a role starts is to run
    # it on a machine, which is not a thing anybody does before a deploy.
    echo "PLAN $name"
    return 0
  fi
  echo "→ Starting $name"
  "$@" &
  pids+=($!)
  echo "  $name PID $!"
}

###############################################################################
### 4) Start services (logs go to stdout for `docker logs`)
###############################################################################

# EXACTLY ONE OF EACH, EVER. See the header: a second copy of either does not
# error, it doubles the work. Never start these on a media node.
if (( runs_singletons )); then
  start ari_manager           python -m api.services.telephony.ari_manager
  start campaign_orchestrator python -m api.services.campaign.campaign_orchestrator
fi

# Spawn FASTAPI_WORKERS independent uvicorn processes on consecutive ports
# starting at UVICORN_BASE_PORT. nginx upstream (configured in setup_remote.sh)
# balances across them with least_conn — better than uvicorn --workers for
# long-lived WebSocket connections, which would otherwise stick to whichever
# worker accepted them first.
#
# These processes ARE the media workers: run_pipeline_telephony is invoked from
# inside the provider's WebSocket handler, so a concurrent call is an asyncio
# task doing VAD and resampling in the same process that serves the dashboard.
# asyncio is single-threaded, so FASTAPI_WORKERS is how many CPU cores can
# carry calls at all — at the default of 1, a 4-vCPU box uses one of them.
if (( runs_uvicorn )); then
  for ((i=0; i<FASTAPI_WORKERS; i++)); do
    port=$((UVICORN_BASE_PORT + i))
    start "uvicorn$i" uvicorn api.app:app --host 0.0.0.0 --port "$port" --workers 1
  done
fi

# Post-call work: costing, reports, backups. Safe to run on several machines --
# arq pulls from a Redis queue, so copies share work rather than duplicating it.
# Kept off media nodes anyway, so a costing job cannot take CPU from a live call.
if (( runs_arq )); then
  for ((i=1; i<=ARQ_WORKERS; i++)); do
    start "arq$i" python -m arq api.tasks.arq.WorkerSettings --custom-log-dict api.tasks.arq.LOG_CONFIG
  done
fi

###############################################################################
### 5) Wait — if any service exits, tear the container down so docker restarts
###############################################################################

if (( PRINT_PLAN )); then
  exit 0
fi

if (( ${#pids[@]} == 0 )); then
  # Nothing to wait on means the role started nothing, which is a
  # misconfiguration rather than a container that should sit idle looking
  # healthy while serving nothing.
  echo "role=$DECIBYL_ROLE started no services." >&2
  exit 1
fi

wait -n
echo "A service exited; tearing down container."
shutdown
