# generated by datamodel-codegen:
#   filename:  decibyl-openapi-HtCTsA.json
#   timestamp: 2026-09-23T12:59:52+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AgentScheduleSlot(BaseModel):
    """
    One window in an agent's week.

    Shaped like the campaign scheduler's slot on purpose: an operator who has
    set calling windows on a campaign should not meet a second, differently
    shaped idea of a week on the agent.
    """

    day_of_week: Annotated[int, Field(ge=0, le=6, title='Day Of Week')]
    start_time: Annotated[
        str, Field(pattern='^([01]\\d|2[0-4]):[0-5]\\d$', title='Start Time')
    ]
    end_time: Annotated[
        str, Field(pattern='^([01]\\d|2[0-4]):[0-5]\\d$', title='End Time')
    ]


class AmbientNoiseConfigurationDefaults(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    enabled: Annotated[bool | None, Field(title='Enabled')] = False
    volume: Annotated[float | None, Field(title='Volume')] = 0.3


class BackchannelConfigurationDefaults(BaseModel):
    """
    A filler ("hmm", "one moment") when the reply is slow to start.

    Off by default: the phrases have to be in the agent's language, and a
    filler in the wrong one is worse than the silence. ``delay_secs`` is how
    long the caller waits before hearing one; ``phrases`` are rotated. See
    services/pipecat/backchannel.py.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    enabled: Annotated[bool | None, Field(title='Enabled')] = False
    delay_secs: Annotated[float | None, Field(title='Delay Secs')] = 1.2
    phrases: Annotated[list[str] | None, Field(title='Phrases')] = None


class BotChannel(Enum):
    """
    Where a bot does its work: on the phone, or in writing.

    Deliberately two values, and deliberately *not* the publisher-facing
    ``Channel`` in ``services/packs/_base.py``. That one names WhatsApp,
    email, Slack and Telegram because a marketplace listing can promise them;
    this one is read by the runtime, and the runtime has exactly two -- the
    pipecat pipeline and the text-chat runner. A third value here would be a
    claim the product cannot keep.

    ``VOICE`` says nothing about direction. Who rings whom is
    ``WorkflowModel.call_type``, which is unchanged: a voice bot is inbound or
    outbound as it always was, and a chat bot is neither, which is the whole
    point of this enum existing rather than a third ``CallType``.

    Stored in ``workflow_configurations``, so no migration and no new column
    on a table telephony reads. Absent means VOICE -- every bot that existed
    before this did was a call bot, and an unset field has to keep meaning
    what it meant.
    """

    voice = 'voice'
    chat = 'chat'


class CalculatorToolDefinition(BaseModel):
    """
    Tool definition for Calculator tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['calculator'], Field(title='Type')]
    """
    Tool type.
    """


class CallDispositionCodes(BaseModel):
    disposition_codes: Annotated[list[str] | None, Field(title='Disposition Codes')] = (
        []
    )


class CallOutcome(BaseModel):
    """
    One label this agent's calls can be classified as afterwards.

    Distinct from ``call_disposition_codes`` on the workflow, which is not
    configuration at all: that column is a registry the pipeline appends to
    with every ``mapped_call_disposition`` it has actually seen, so the calls
    list can offer a dropdown of codes that occurred. This is the taxonomy a
    business *decides on* — the outcomes it wants sorted by, whether or not a
    call has produced one yet.

    Per workflow, because the outcomes are. A clinic books appointments, a
    lending agent gets a payment promise, an NDR agent confirms an address.
    Both Vapi and Bolna let you define the shape here rather than shipping a
    fixed set, and for the same reason: there isn't one.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    code: Annotated[str | None, Field(max_length=40, title='Code')] = ''
    label: Annotated[str | None, Field(max_length=60, title='Label')] = ''
    when: Annotated[str | None, Field(max_length=200, title='When')] = ''


class ConnectedAccountId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, title='Connected Account Id')]
    """
    Which connected account this tool acts on, e.g. a specific doctor's calendar. Omit to use the organization's default.
    """


class ContactListRequest(BaseModel):
    name: Annotated[str, Field(max_length=128, min_length=1, title='Name')]
    description: Annotated[str | None, Field(title='Description')] = None


class ContactListResponse(BaseModel):
    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')] = None
    contact_count: Annotated[int | None, Field(title='Contact Count')] = 0


class Category(Enum):
    """
    Tool category. Must match definition.type.
    """

    http_api = 'http_api'
    end_call = 'end_call'
    transfer_call = 'transfer_call'
    calculator = 'calculator'
    native = 'native'
    integration = 'integration'
    mcp = 'mcp'
    google_calendar = 'google_calendar'
    rate_table = 'rate_table'
    composio = 'composio'
    web = 'web'


class Icon(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Icon')] = 'globe'
    """
    Lucide icon identifier.
    """


class IconColor(RootModel[str]):
    root: Annotated[str, Field(max_length=7, title='Icon Color')] = '#3B82F6'
    """
    Hex color for the tool icon.
    """


class CreateWorkflowRequest(BaseModel):
    name: Annotated[str, Field(title='Name')]
    workflow_definition: Annotated[dict[str, Any], Field(title='Workflow Definition')]


class CreatedByResponse(BaseModel):
    """
    Response schema for the user who created a tool.
    """

    id: Annotated[int, Field(title='Id')]
    provider_id: Annotated[str, Field(title='Provider Id')]


class CredentialResponse(BaseModel):
    """
    Response schema for a webhook credential (never includes sensitive data).
    """

    uuid: Annotated[str, Field(title='Uuid')]
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')]
    credential_type: Annotated[str, Field(title='Credential Type')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime | None, Field(title='Updated At')]


class DisplayOptions(BaseModel):
    """
    Conditional visibility rules.

    `show` keys are AND-combined: this property is visible only when EVERY
    referenced field's value matches one of the listed values.

    `hide` keys are OR-combined: this property is hidden when ANY referenced
    field's value matches one of the listed values.

    Example:
        DisplayOptions(show={"extraction_enabled": [True]})
        DisplayOptions(show={"greeting_type": ["audio"]})
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    show: Annotated[dict[str, list[Any]] | None, Field(title='Show')] = None
    hide: Annotated[dict[str, list[Any]] | None, Field(title='Hide')] = None


class DocumentResponseSchema(BaseModel):
    """
    Response schema for document metadata.
    """

    id: Annotated[int, Field(title='Id')]
    document_uuid: Annotated[str, Field(title='Document Uuid')]
    filename: Annotated[str, Field(title='Filename')]
    file_size_bytes: Annotated[int, Field(title='File Size Bytes')]
    file_hash: Annotated[str, Field(title='File Hash')]
    mime_type: Annotated[str, Field(title='Mime Type')]
    processing_status: Annotated[str, Field(title='Processing Status')]
    processing_error: Annotated[str | None, Field(title='Processing Error')] = None
    needs_reingest: Annotated[bool | None, Field(title='Needs Reingest')] = False
    total_chunks: Annotated[int, Field(title='Total Chunks')]
    retrieval_mode: Annotated[str | None, Field(title='Retrieval Mode')] = 'chunked'
    custom_metadata: Annotated[dict[str, Any], Field(title='Custom Metadata')]
    docling_metadata: Annotated[dict[str, Any], Field(title='Docling Metadata')]
    source_url: Annotated[str | None, Field(title='Source Url')] = None
    scope: Annotated[str | None, Field(title='Scope')] = 'library'
    folder_id: Annotated[int | None, Field(title='Folder Id')] = None
    workflow_id: Annotated[int | None, Field(title='Workflow Id')] = None
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    organization_id: Annotated[int, Field(title='Organization Id')]
    created_by: Annotated[int, Field(title='Created By')]
    is_active: Annotated[bool, Field(title='Is Active')]


class MessageType(Enum):
    """
    Type of goodbye message.
    """

    none = 'none'
    custom = 'custom'
    audio = 'audio'


class EndCallConfig(BaseModel):
    """
    Configuration for End Call tools.
    """

    messageType: Annotated[MessageType | None, Field(title='Messagetype')] = 'none'
    """
    Type of goodbye message.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before ending the call.
    """
    audioRecordingId: Annotated[str | None, Field(title='Audiorecordingid')] = None
    """
    Recording ID for audio goodbye message.
    """
    endCallReason: Annotated[bool | None, Field(title='Endcallreason')] = False
    """
    When enabled, the model must provide a reason for ending the call. The reason is set as call disposition and added to call tags.
    """
    endCallReasonDescription: Annotated[
        str | None, Field(title='Endcallreasondescription')
    ] = None
    """
    Description shown to the model for the reason parameter. Used only when endCallReason is enabled.
    """


class EndCallToolDefinition(BaseModel):
    """
    Tool definition for End Call tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['end_call'], Field(title='Type')]
    """
    Tool type.
    """
    config: EndCallConfig
    """
    End Call configuration.
    """


class FallbackServiceConfiguration(BaseModel):
    """
    One backup in an ordered chain, tried when the one before it fails.

    Deliberately thin. A backup is chosen to keep a live call alive, not to be
    tuned -- so it names a provider and, where the provider needs them, a model
    and a voice, and takes the provider's defaults for everything else. The key
    comes from the account's vault at dial time, so a backup can only be a
    provider this account can actually authenticate to.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    provider: Annotated[str, Field(min_length=1, title='Provider')]
    model: Annotated[str | None, Field(title='Model')] = ''
    voice: Annotated[str | None, Field(title='Voice')] = ''
    language: Annotated[str | None, Field(title='Language')] = ''


class GoogleCalendarToolDefinition(BaseModel):
    """
    Tool definition for creating an event on the organization's connected
    Google Calendar. No config: unlike an HTTP API tool there is no URL,
    auth, or parameter builder to fill in — the parameter shape is fixed
    (see api/services/integrations/google_calendar/client.py) and which
    calendar it writes to is decided once, org-wide, by the Connect Google
    Calendar flow, not per-tool.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['google_calendar'], Field(title='Type')]
    """
    Tool type.
    """


class GraphConstraints(BaseModel):
    """
    Per-node-type graph rules. WorkflowGraph enforces these at validation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    min_incoming: Annotated[int | None, Field(title='Min Incoming')] = None
    max_incoming: Annotated[int | None, Field(title='Max Incoming')] = None
    min_outgoing: Annotated[int | None, Field(title='Min Outgoing')] = None
    max_outgoing: Annotated[int | None, Field(title='Max Outgoing')] = None
    min_instances: Annotated[int | None, Field(title='Min Instances')] = None
    max_instances: Annotated[int | None, Field(title='Max Instances')] = None


class Method(Enum):
    """
    HTTP method to use for the request.
    """

    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'


class TimeoutMs(RootModel[int]):
    root: Annotated[int, Field(ge=1, title='Timeout Ms')] = 5000
    """
    Request timeout in milliseconds.
    """


class CustomMessageType(Enum):
    """
    Type of custom message.
    """

    text = 'text'
    audio = 'audio'


class InitiateCallRequest(BaseModel):
    workflow_id: Annotated[int, Field(title='Workflow Id')]
    workflow_run_id: Annotated[int | None, Field(title='Workflow Run Id')] = None
    phone_number: Annotated[str | None, Field(title='Phone Number')] = None
    telephony_configuration_id: Annotated[
        int | None, Field(title='Telephony Configuration Id')
    ] = None
    from_phone_number_id: Annotated[int | None, Field(title='From Phone Number Id')] = (
        None
    )


class LibraryExtraction(BaseModel):
    """
    One catalog entry, and the ``ExtractionSpec`` it seeds.
    """

    key: Annotated[str, Field(title='Key')]
    """
    Stable id for this entry. Not stored on the node.
    """
    display_name: Annotated[str, Field(title='Display Name')]
    """
    What the picker lists it as.
    """
    category: Annotated[str, Field(title='Category')]
    """
    Section heading in the picker.
    """
    summary: Annotated[str, Field(title='Summary')]
    """
    One line on what this pulls out of a call.
    """
    name: Annotated[str, Field(title='Name')]
    """
    Seeds ExtractionSpec.name — the JSON key.
    """
    prompt: Annotated[str, Field(title='Prompt')]
    """
    Seeds ExtractionSpec.prompt.
    """
    answer_type: Annotated[str | None, Field(title='Answer Type')] = 'free_text'
    predefined_options: Annotated[str | None, Field(title='Predefined Options')] = ''
    expected_format: Annotated[str | None, Field(title='Expected Format')] = 'text'


class LibraryOptions(BaseModel):
    """
    Names a catalog of ready-made values the editor can offer for a field.

    The renderer stays generic: it shows a "Browse library" control when this
    is set, fetches the named catalog, and appends whatever the user picks to
    the field's existing value. Which catalog, and what is in it, are decided
    on the backend beside the code that consumes the values — the alternative
    is a picker hard-coded against one field name, which is how the second
    field with a library ends up copy-pasting the first one's dialog.

    Picking from a library copies. Nothing is referenced by id afterwards, so
    a value an operator has since tuned is never silently replaced by an edit
    to the catalog.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    catalog: Annotated[str, Field(title='Catalog')]
    """
    Catalog id, served by GET /api/v1/extraction-library/{catalog}.
    """


class LibraryToolParameter(BaseModel):
    """
    One parameter the agent fills in, seeding a `ToolParameter`.
    """

    name: Annotated[str, Field(title='Name')]
    type: Annotated[str | None, Field(title='Type')] = 'string'
    description: Annotated[str, Field(title='Description')]
    required: Annotated[bool | None, Field(title='Required')] = True


class McpToolConfig(BaseModel):
    """
    Configuration for a customer MCP server tool definition.
    """

    transport: Annotated[Literal['streamable_http'], Field(title='Transport')] = (
        'streamable_http'
    )
    """
    MCP transport protocol.
    """
    url: Annotated[str, Field(title='Url')]
    """
    MCP server URL. Must use http:// or https://.
    """
    credential_uuid: Annotated[str | None, Field(title='Credential Uuid')] = None
    """
    Reference to an external credential for MCP server auth.
    """
    tools_filter: Annotated[list[str] | None, Field(title='Tools Filter')] = None
    """
    Allowlist of MCP tool names to expose. On create, empty is filled with the server's read-only tools; on update, empty exposes all.
    """
    timeout_secs: Annotated[int | None, Field(ge=0, title='Timeout Secs')] = 30
    """
    Connection timeout in seconds.
    """
    sse_read_timeout_secs: Annotated[
        int | None, Field(ge=0, title='Sse Read Timeout Secs')
    ] = 300
    """
    SSE read timeout in seconds.
    """
    discovered_tools: Annotated[
        list[dict[str, Any]] | None, Field(title='Discovered Tools')
    ] = None
    """
    Server-managed cache of the MCP server's tool catalog [{name, description}]. Populated best-effort by the backend.
    """


class McpToolDefinition(BaseModel):
    """
    Persisted MCP tool definition.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['mcp'], Field(title='Type')]
    """
    Tool type.
    """
    config: McpToolConfig
    """
    MCP server configuration.
    """


class NodeCategory(Enum):
    """
    Drives grouping in the AddNodePanel UI.
    """

    call_node = 'call_node'
    global_node = 'global_node'
    trigger = 'trigger'
    integration = 'integration'


class NodeExample(BaseModel):
    """
    A worked example LLMs can pattern-match. Keep small and realistic.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')] = None
    data: Annotated[dict[str, Any], Field(title='Data')]


class NoiseSuppressionConfigurationDefaults(BaseModel):
    """
    Noise off the caller's audio before the agent hears it.

    On by default: the people who call an Indian business are on a road, in a
    shop, on a bus. ``level`` is the share of the denoised signal in the blend
    the agent hears, 20 to 100 — see services/pipecat/noise_suppression.py.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    level: Annotated[int | None, Field(ge=20, le=100, title='Level')] = 100


class NumberInputOptions(BaseModel):
    """
    Renderer hints for numeric inputs.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    fractional: Annotated[bool | None, Field(title='Fractional')] = False
    """
    Allow arbitrary fractional values via step='any'.
    """


class OutcomeAction(BaseModel):
    """
    Something the agent does once the call is over.

    The other half of :class:`CallOutcome`. That one names what a call can turn
    out to be; this one says what should happen when it turns out that way --
    append the booking to the clinic's sheet, raise the CRM record, send the
    payment link.

    **After the call, not during, and that is the point.** The same action is
    already possible as a tool the agent calls mid-conversation, and for most
    of what a business wants it is the wrong shape: writing a row takes a
    second or more of a live line, and a caller listening to silence while we
    talk to Google is a worse experience than one whose booking is filed
    thirty seconds after they hang up. Nothing here is on the caller's clock,
    so nothing here needs a filler phrase, a timeout budget, or a decision from
    the model about whether it is worth the wait.

    Deterministic, too. A tool the agent *may* call is a tool it sometimes does
    not, and "always log the booking" cannot be built out of a model's
    judgement. This fires on the outcome code, or on every call.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    tool_uuid: Annotated[str, Field(max_length=64, min_length=1, title='Tool Uuid')]
    when: Annotated[list[str] | None, Field(max_length=30, title='When')] = None
    arguments: Annotated[dict[str, str] | None, Field(title='Arguments')] = None
    enabled: Annotated[bool | None, Field(title='Enabled')] = True


class Type(Enum):
    """
    JSON type for the resolved value.
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    object = 'object'
    array = 'array'


class PresetToolParameter(BaseModel):
    """
    A parameter injected by Decibyl at runtime.
    """

    name: Annotated[str, Field(title='Name')]
    """
    Parameter name used as a key in the request body.
    """
    type: Annotated[Type, Field(title='Type')]
    """
    JSON type for the resolved value.
    """
    value_template: Annotated[str, Field(title='Value Template')]
    """
    Fixed value or template, e.g. {{initial_context.phone_number}}.
    """
    required: Annotated[bool | None, Field(title='Required')] = True
    """
    Whether the parameter must resolve to a non-empty value.
    """


class ColumnSpan(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=12, title='Column Span')]
    """
    Number of columns to occupy in the editor's 12-column grid.
    """


class PropertyLayoutOptions(BaseModel):
    """
    Renderer layout hints for a property in the node editor.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    column_span: Annotated[ColumnSpan | None, Field(title='Column Span')] = None
    """
    Number of columns to occupy in the editor's 12-column grid.
    """


class PropertyOption(BaseModel):
    """
    An option in an `options` or `multi_options` dropdown.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[str | int | bool | float, Field(title='Value')]
    label: Annotated[str, Field(title='Label')]
    description: Annotated[str | None, Field(title='Description')] = None


class PropertyRendererOptions(BaseModel):
    """
    Typed renderer metadata for node properties.

    Add new renderer behavior here instead of using free-form property metadata.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    layout: PropertyLayoutOptions | None = None
    number_input: NumberInputOptions | None = None
    library: LibraryOptions | None = None


class PropertyType(Enum):
    """
    Bounded vocabulary of property types the renderer dispatches on.

    Adding a value here requires a matching arm in the frontend
    `<PropertyInput>` switch and (where relevant) the SDK codegen template.
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    options = 'options'
    multi_options = 'multi_options'
    fixed_collection = 'fixed_collection'
    json = 'json'
    tool_refs = 'tool_refs'
    document_refs = 'document_refs'
    recording_ref = 'recording_ref'
    credential_ref = 'credential_ref'
    agent_ref = 'agent_ref'
    mention_textarea = 'mention_textarea'
    url = 'url'


class RateTableConfig(BaseModel):
    """
    An operator's rate card: grids, the rules around them, and its wording.

    Loosely typed on purpose below the top level. A card is the operator's own
    data and its shape varies -- two grids or seven, half-kilo bands or whole
    ones -- so the schema fixes the parts the lookup depends on and leaves the
    numbers alone. What it will not accept is a card with no grids, because
    that one produces a tool that refuses every question at call time instead
    of failing here, where somebody is looking.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    currency: Annotated[str | None, Field(max_length=16, title='Currency')] = ''
    """
    Currency the amounts are in.
    """
    grids: Annotated[dict[str, dict[str, dict[str, float]]], Field(title='Grids')]
    """
    The card itself: variant -> band -> series -> amount. For a courier that reads kind -> weight -> zone -> price.
    """
    default_variant: Annotated[str | None, Field(title='Default Variant')] = None
    """
    Grid to use when the model does not name one.
    """
    crossovers: Annotated[
        dict[str, dict[str, Any]] | None, Field(title='Crossovers')
    ] = None
    """
    Rules of the form {variant: {above_band: N, use: other_variant}}, for cards where one kind starts pricing as another past a size.
    """
    overflow: Annotated[dict[str, Any] | None, Field(title='Overflow')] = None
    """
    Per-unit metering past the last band: {from: N, tiers: [{upto: N|null, per_unit: {series: rate}}]}.
    """
    aliases: Annotated[dict[str, str] | None, Field(title='Aliases')] = None
    """
    What a caller might say, mapped to a column of the card. Matching ignores case and punctuation.
    """
    labels: Annotated[dict[str, str] | None, Field(title='Labels')] = None
    """
    How the tool is described to the agent: function_name, description, destination, band, variant.
    """


class RateTableToolDefinition(BaseModel):
    """
    Tool definition for a rate-card lookup.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['rate_table'], Field(title='Type')]
    """
    Tool type.
    """
    config: RateTableConfig
    """
    The operator's rate card.
    """


class RecordingConfigurationDefaults(BaseModel):
    """
    Whether the call's audio is kept.

    On by default: the recording is what a call review, a QA grade and a
    dispute are settled with. Off means no audio is buffered or uploaded for
    the call — the transcript, the usage and the outcome are still kept, and
    the agent stops telling the caller the call is recorded, because it isn't.
    For the clinic or the lender whose compliance team says "no voice data at
    rest".
    """

    model_config = ConfigDict(
        extra='allow',
    )
    enabled: Annotated[bool | None, Field(title='Enabled')] = True


class RecordingResponseSchema(BaseModel):
    """
    Response schema for a single recording.
    """

    id: Annotated[int, Field(title='Id')]
    recording_id: Annotated[str, Field(title='Recording Id')]
    workflow_id: Annotated[int | None, Field(title='Workflow Id')] = None
    organization_id: Annotated[int, Field(title='Organization Id')]
    tts_provider: Annotated[str | None, Field(title='Tts Provider')] = None
    tts_model: Annotated[str | None, Field(title='Tts Model')] = None
    tts_voice_id: Annotated[str | None, Field(title='Tts Voice Id')] = None
    transcript: Annotated[str, Field(title='Transcript')]
    storage_key: Annotated[str, Field(title='Storage Key')]
    storage_backend: Annotated[str, Field(title='Storage Backend')]
    metadata: Annotated[dict[str, Any], Field(title='Metadata')]
    created_by: Annotated[int, Field(title='Created By')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    is_active: Annotated[bool, Field(title='Is Active')]


class Type1(Enum):
    """
    JSON type for the parameter value.
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    object = 'object'
    array = 'array'


class ToolParameter(BaseModel):
    """
    A parameter that the tool accepts from the model at call time.
    """

    name: Annotated[str, Field(title='Name')]
    """
    Parameter name used as a key in the tool request body.
    """
    type: Annotated[Type1, Field(title='Type')]
    """
    JSON type for the parameter value.
    """
    description: Annotated[str, Field(title='Description')]
    """
    Description shown to the model for this parameter.
    """
    required: Annotated[bool | None, Field(title='Required')] = True
    """
    Whether this parameter is required when the tool is called.
    """


class ToolResponse(BaseModel):
    """
    Response schema for a reusable tool.
    """

    id: Annotated[int, Field(title='Id')]
    tool_uuid: Annotated[str, Field(title='Tool Uuid')]
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')]
    category: Annotated[str, Field(title='Category')]
    icon: Annotated[str | None, Field(title='Icon')]
    icon_color: Annotated[str | None, Field(title='Icon Color')]
    status: Annotated[str, Field(title='Status')]
    definition: Annotated[dict[str, Any], Field(title='Definition')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime | None, Field(title='Updated At')]
    created_by: CreatedByResponse | None = None


class DestinationSource(Enum):
    """
    Whether transfer destination is static/template or resolved by HTTP.
    """

    static = 'static'
    dynamic = 'dynamic'


class MessageType1(Enum):
    """
    Type of message to play before transfer.
    """

    none = 'none'
    custom = 'custom'
    audio = 'audio'


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]
    input: Annotated[Any | None, Field(title='Input')] = None
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None


class MaxPagesPerRun(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=200, title='Max Pages Per Run')]
    """
    Pages one run may read; blank means the platform's cap.
    """


class WebToolConfig(BaseModel):
    """
    What an agent's web tool is kept to (OP-2). Both optional: an empty
    list is the whole web, and no page figure is the platform's cap.
    """

    allowed_domains: Annotated[
        list[str] | None, Field(max_length=50, title='Allowed Domains')
    ] = None
    """
    Sites this agent may search and read, as hosts (acme.example). Empty means any site the platform's rules allow.
    """
    max_pages_per_run: Annotated[
        MaxPagesPerRun | None, Field(title='Max Pages Per Run')
    ] = None
    """
    Pages one run may read; blank means the platform's cap.
    """


class WebToolDefinition(BaseModel):
    """
    Tool definition for the built-in web tools (OP-1, OP-2).

    The search runs on the platform's own key and the fetch is the
    platform's own fetcher, so there is nothing to fill in unless the agent
    is to be kept to a list of sites or to fewer pages a run. One tool row
    gives the agent both ``web_search`` and ``web_fetch`` (search only on a
    voice call, where a page's worth of text has no place). Each search is
    charged as a tool call plus the vendor's price passed through at cost;
    a fetch is a tool call.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['web'], Field(title='Type')]
    """
    Tool type.
    """
    config: WebToolConfig | None = None
    """
    Sites and page cap, when the agent has them.
    """


class TurnStartStrategy(Enum):
    default = 'default'
    min_words = 'min_words'
    provisional_vad = 'provisional_vad'
    vad = 'vad'


class TurnStopStrategy(Enum):
    transcription = 'transcription'
    turn_analyzer = 'turn_analyzer'


class CallerEnvironment(Enum):
    quiet = 'quiet'
    normal = 'normal'
    noisy = 'noisy'


class WorkflowListResponse(BaseModel):
    """
    Lightweight response for workflow listings (excludes large fields).
    """

    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    status: Annotated[str, Field(title='Status')]
    is_live: Annotated[bool | None, Field(title='Is Live')] = True
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    total_runs: Annotated[int, Field(title='Total Runs')]
    folder_id: Annotated[int | None, Field(title='Folder Id')] = None
    workflow_uuid: Annotated[str | None, Field(title='Workflow Uuid')] = None
    handle: Annotated[str | None, Field(title='Handle')] = None
    is_squad: Annotated[bool | None, Field(title='Is Squad')] = False


class WorkflowResponse(BaseModel):
    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    status: Annotated[str, Field(title='Status')]
    is_live: Annotated[bool | None, Field(title='Is Live')] = True
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    workflow_definition: Annotated[dict[str, Any], Field(title='Workflow Definition')]
    current_definition_id: Annotated[int | None, Field(title='Current Definition Id')]
    template_context_variables: Annotated[
        dict[str, Any] | None, Field(title='Template Context Variables')
    ] = None
    call_disposition_codes: CallDispositionCodes | None = None
    total_runs: Annotated[int | None, Field(title='Total Runs')] = None
    workflow_configurations: Annotated[
        dict[str, Any] | None, Field(title='Workflow Configurations')
    ] = None
    version_number: Annotated[int | None, Field(title='Version Number')] = None
    version_status: Annotated[str | None, Field(title='Version Status')] = None
    workflow_uuid: Annotated[str | None, Field(title='Workflow Uuid')] = None


class AgentSchedule(BaseModel):
    """
    The hours an agent keeps, as something the platform can enforce.

    Narayani's opening hours live in its prompt -- "9:30 to 1:00 is when the
    clinic is open" -- so the agent can *say* them and the platform cannot
    *keep* them. A call at eleven at night is answered, a slot is agreed, and
    nobody at the clinic will honour it.

    Off by default, and off means always open: an agent nobody has scheduled
    behaves exactly as it does today. Everything ambiguous resolves to open as
    well -- see services/workflow/agent_hours.py -- because taking a number off
    the air is a worse failure than answering a call out of hours.
    """

    enabled: Annotated[bool | None, Field(title='Enabled')] = False
    timezone: Annotated[str | None, Field(title='Timezone')] = 'Asia/Kolkata'
    slots: Annotated[
        list[AgentScheduleSlot] | None, Field(max_length=50, title='Slots')
    ] = None


class ComposioToolConfig(BaseModel):
    """
    Configuration for one tool on one Composio-connected app.

    Deliberately one tool per Decibyl tool rather than a whole toolkit. A
    toolkit is hundreds of slugs; handing an agent all of Gmail means handing
    it GMAIL_DELETE_MESSAGE, and the operator who wanted "send the customer
    their invoice" did not ask for that. Naming the slug is also what makes the
    parameters knowable: we can state what the model must supply instead of
    letting it guess at a catalog.

    There is no credential field on purpose. *Which organization* this acts for
    is not configuration -- it is derived from the caller at execution time
    (see services/integrations/composio/client.py), so no value stored here can
    reach another tenant's data.

    ``connected_account_id`` is a different question and belongs here. A clinic
    with three doctors connects three calendars, all under the one organization
    identity, and "Book with Dr Ramesh" and "Book with Dr Priya" are then two
    tools differing only by this field. Because an agent holds a list of tools
    per node, that also settles permissions without a permission system: an
    agent that was not given the second tool cannot reach the second calendar.
    """

    toolkit: Annotated[str, Field(title='Toolkit')]
    """
    Composio toolkit slug, e.g. GMAIL or GOOGLESHEETS.
    """
    tool_slug: Annotated[str, Field(title='Tool Slug')]
    """
    Composio tool slug, e.g. GMAIL_SEND_EMAIL.
    """
    connected_account_id: Annotated[
        ConnectedAccountId | None, Field(title='Connected Account Id')
    ] = None
    """
    Which connected account this tool acts on, e.g. a specific doctor's calendar. Omit to use the organization's default.
    """
    parameters: Annotated[list[ToolParameter] | None, Field(title='Parameters')] = None
    """
    Arguments the agent supplies, passed through to the tool.
    """
    timeout_secs: Annotated[
        float | None, Field(gt=0.0, le=30.0, title='Timeout Secs')
    ] = 12.0
    """
    How long to wait for the tool before giving up, in seconds.
    """


class ComposioToolDefinition(BaseModel):
    """
    Tool definition for running one Composio tool.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['composio'], Field(title='Type')]
    """
    Tool type.
    """
    config: ComposioToolConfig


class DocumentListResponseSchema(BaseModel):
    """
    Response schema for list of documents.
    """

    documents: Annotated[list[DocumentResponseSchema], Field(title='Documents')]
    total: Annotated[int, Field(title='Total')]
    limit: Annotated[int, Field(title='Limit')]
    offset: Annotated[int, Field(title='Offset')]


class ExtractionLibraryResponse(BaseModel):
    """
    The catalog, and the order its sections should be shown in.
    """

    catalog: Annotated[str, Field(title='Catalog')]
    categories: Annotated[list[str], Field(title='Categories')]
    extractions: Annotated[list[LibraryExtraction], Field(title='Extractions')]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class HttpApiConfig(BaseModel):
    """
    Configuration for HTTP API tools.
    """

    method: Annotated[Method, Field(title='Method')]
    """
    HTTP method to use for the request.
    """
    url: Annotated[str, Field(title='Url')]
    """
    Target HTTP or HTTPS URL.
    """
    headers: Annotated[dict[str, str] | None, Field(title='Headers')] = None
    """
    Static headers to include with every request.
    """
    credential_uuid: Annotated[str | None, Field(title='Credential Uuid')] = None
    """
    Reference to an external credential for request authentication.
    """
    parameters: Annotated[list[ToolParameter] | None, Field(title='Parameters')] = None
    """
    Parameters the model must provide when calling this tool.
    """
    preset_parameters: Annotated[
        list[PresetToolParameter] | None, Field(title='Preset Parameters')
    ] = None
    """
    Parameters injected by Decibyl from fixed values or workflow context templates.
    """
    timeout_ms: Annotated[
        TimeoutMs | None, Field(title='Timeout Ms', validate_default=True)
    ] = 5000
    """
    Request timeout in milliseconds.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play after tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """
    mock_response: Annotated[dict[str, Any] | None, Field(title='Mock Response')] = None
    """
    Answer the model with this instead of calling the URL. For building and demonstrating an agent before the backend exists.
    """


class HttpApiToolDefinition(BaseModel):
    """
    Tool definition for HTTP API tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['http_api'], Field(title='Type')]
    """
    Tool type.
    """
    config: HttpApiConfig
    """
    HTTP API configuration.
    """


class HttpTransferResolverConfig(BaseModel):
    """
    HTTP endpoint used to resolve transfer destination at call time.
    """

    type: Annotated[Literal['http'], Field(title='Type')] = 'http'
    """
    Resolver type.
    """
    url: Annotated[str, Field(title='Url')]
    """
    HTTP or HTTPS endpoint for transfer resolution.
    """
    headers: Annotated[dict[str, str] | None, Field(title='Headers')] = None
    """
    Static headers to include with every resolver request.
    """
    credential_uuid: Annotated[str | None, Field(title='Credential Uuid')] = None
    """
    Reference to an external credential for resolver authentication.
    """
    timeout_ms: Annotated[int | None, Field(ge=500, le=5000, title='Timeout Ms')] = 3000
    """
    Resolver request timeout in milliseconds.
    """
    wait_message: Annotated[str | None, Field(title='Wait Message')] = None
    """
    Optional short message played while Decibyl resolves routing.
    """
    parameters: Annotated[list[ToolParameter] | None, Field(title='Parameters')] = None
    """
    Parameters the model may provide when calling this transfer tool.
    """
    preset_parameters: Annotated[
        list[PresetToolParameter] | None, Field(title='Preset Parameters')
    ] = None
    """
    Parameters injected by Decibyl from fixed values or workflow context templates.
    """


class LibraryTool(BaseModel):
    """
    One catalogue entry, and the `http_api` tool it seeds.
    """

    key: Annotated[str, Field(title='Key')]
    """
    Stable id for this entry. Not stored on the tool.
    """
    vendor: Annotated[str, Field(title='Vendor')]
    """
    Section heading in the picker.
    """
    display_name: Annotated[str, Field(title='Display Name')]
    """
    What the picker lists it as.
    """
    summary: Annotated[str, Field(title='Summary')]
    """
    One line on what it does during a call.
    """
    tool_name: Annotated[str, Field(title='Tool Name')]
    tool_description: Annotated[str, Field(title='Tool Description')]
    method: Annotated[str | None, Field(title='Method')] = 'GET'
    url: Annotated[str, Field(title='Url')]
    parameters: Annotated[
        list[LibraryToolParameter] | None, Field(title='Parameters')
    ] = None
    setup_note: Annotated[str | None, Field(title='Setup Note')] = ''


class PropertySpec(BaseModel):
    """
    Single field on a node.

    `description` is HUMAN-FACING — shown under the field in the edit
    dialog. Keep it concise and explain what the field does.

    `llm_hint` is LLM-FACING — appears only in the `get_node_type` MCP
    response and in SDK schema output. Use it for catalog tool references
    (e.g., "Use `list_recordings`"), array shape, expected value idioms,
    or anything that would be noise in the UI. Optional; omit when the
    `description` already suffices for both audiences.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    type: PropertyType
    display_name: Annotated[str, Field(title='Display Name')]
    description: Annotated[str, Field(min_length=1, title='Description')]
    """
    Human-facing explanation shown in the UI.
    """
    llm_hint: Annotated[str | None, Field(title='Llm Hint')] = None
    """
    LLM-only guidance; omitted from the UI.
    """
    default: Annotated[Any | None, Field(title='Default')] = None
    required: Annotated[bool | None, Field(title='Required')] = False
    placeholder: Annotated[str | None, Field(title='Placeholder')] = None
    display_options: DisplayOptions | None = None
    options: Annotated[list[PropertyOption] | None, Field(title='Options')] = None
    properties: Annotated[list[PropertySpec] | None, Field(title='Properties')] = None
    min_value: Annotated[float | None, Field(title='Min Value')] = None
    max_value: Annotated[float | None, Field(title='Max Value')] = None
    min_length: Annotated[int | None, Field(title='Min Length')] = None
    max_length: Annotated[int | None, Field(title='Max Length')] = None
    pattern: Annotated[str | None, Field(title='Pattern')] = None
    editor: Annotated[str | None, Field(title='Editor')] = None
    renderer_options: PropertyRendererOptions | None = None


class RecordingListResponseSchema(BaseModel):
    """
    Response schema for list of recordings.
    """

    recordings: Annotated[list[RecordingResponseSchema], Field(title='Recordings')]
    total: Annotated[int, Field(title='Total')]


class ToolLibraryResponse(BaseModel):
    catalog: Annotated[str, Field(title='Catalog')]
    vendors: Annotated[list[str], Field(title='Vendors')]
    tools: Annotated[list[LibraryTool], Field(title='Tools')]


class TransferCallConfig(BaseModel):
    """
    Configuration for Transfer Call tools.
    """

    destination_source: Annotated[
        DestinationSource | None, Field(title='Destination Source')
    ] = 'static'
    """
    Whether transfer destination is static/template or resolved by HTTP.
    """
    destination: Annotated[str | None, Field(title='Destination')] = ''
    """
    Phone number, SIP endpoint, or template to transfer the call to, e.g. +1234567890, PJSIP/1234, or {{initial_context.transfer_destination}}.
    """
    messageType: Annotated[MessageType1 | None, Field(title='Messagetype')] = 'none'
    """
    Type of message to play before transfer.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before transferring.
    """
    audioRecordingId: Annotated[str | None, Field(title='Audiorecordingid')] = None
    """
    Recording ID for audio message before transfer.
    """
    timeout: Annotated[int | None, Field(ge=5, le=120, title='Timeout')] = 30
    """
    Maximum seconds to wait for the destination to answer.
    """
    parameters: Annotated[list[ToolParameter] | None, Field(title='Parameters')] = None
    """
    Parameters the model may provide when calling this transfer tool, for example state, department, or transfer reason.
    """
    resolver: HttpTransferResolverConfig | None = None
    """
    Optional resolver that determines transfer routing at call time.
    """


class TransferCallToolDefinition(BaseModel):
    """
    Tool definition for Transfer Call tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['transfer_call'], Field(title='Type')]
    """
    Tool type.
    """
    config: TransferCallConfig
    """
    Transfer Call configuration.
    """


class WorkflowConfigurationDefaults(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    channel: BotChannel | None = 'voice'
    ambient_noise_configuration: AmbientNoiseConfigurationDefaults | None = None
    noise_suppression_configuration: NoiseSuppressionConfigurationDefaults | None = None
    recording_configuration: RecordingConfigurationDefaults | None = None
    backchannel_configuration: BackchannelConfigurationDefaults | None = None
    end_call_phrases: Annotated[list[str] | None, Field(title='End Call Phrases')] = (
        None
    )
    end_call_farewell: Annotated[str | None, Field(title='End Call Farewell')] = None
    agent_can_end_call: Annotated[bool | None, Field(title='Agent Can End Call')] = (
        False
    )
    max_call_duration: Annotated[
        int | None, Field(gt=0, le=1200, title='Max Call Duration')
    ] = 300
    max_user_idle_timeout: Annotated[
        float | None, Field(title='Max User Idle Timeout')
    ] = 10.0
    smart_turn_stop_secs: Annotated[
        float | None, Field(title='Smart Turn Stop Secs')
    ] = 2.0
    turn_start_strategy: Annotated[
        TurnStartStrategy | None, Field(title='Turn Start Strategy')
    ] = 'default'
    turn_start_min_words: Annotated[int | None, Field(title='Turn Start Min Words')] = 3
    provisional_vad_pause_secs: Annotated[
        float | None, Field(title='Provisional Vad Pause Secs')
    ] = 1.5
    turn_stop_strategy: Annotated[
        TurnStopStrategy | None, Field(title='Turn Stop Strategy')
    ] = 'transcription'
    user_speech_timeout: Annotated[
        float | None, Field(ge=0.15, le=3.0, title='User Speech Timeout')
    ] = 0.4
    caller_environment: Annotated[
        CallerEnvironment | None, Field(title='Caller Environment')
    ] = 'normal'
    dictionary: Annotated[str | None, Field(title='Dictionary')] = ''
    agent_schedule: AgentSchedule | None = None
    interruption_backoff_secs: Annotated[
        float | None, Field(ge=0.0, le=3.0, title='Interruption Backoff Secs')
    ] = 0.0
    context_compaction_enabled: Annotated[
        bool | None, Field(title='Context Compaction Enabled')
    ] = False
    fallback_tts: Annotated[
        list[FallbackServiceConfiguration] | None,
        Field(max_length=2, title='Fallback Tts'),
    ] = None
    fallback_stt: Annotated[
        list[FallbackServiceConfiguration] | None,
        Field(max_length=2, title='Fallback Stt'),
    ] = None
    call_outcomes: Annotated[
        list[CallOutcome] | None, Field(max_length=30, title='Call Outcomes')
    ] = None
    outcome_actions: Annotated[
        list[OutcomeAction] | None, Field(max_length=20, title='Outcome Actions')
    ] = None
    follow_caller_language: Annotated[
        bool | None, Field(title='Follow Caller Language')
    ] = False
    accept_keypad_input: Annotated[bool | None, Field(title='Accept Keypad Input')] = (
        False
    )
    speak_like_callers: Annotated[bool | None, Field(title='Speak Like Callers')] = True
    agent_languages: Annotated[list[str] | None, Field(title='Agent Languages')] = None


class CreateToolRequest(BaseModel):
    """
    Request schema for creating a reusable tool.
    """

    name: Annotated[str, Field(max_length=255, title='Name')]
    """
    Display name for the tool.
    """
    description: Annotated[str | None, Field(title='Description')] = None
    """
    Description shown to the agent when deciding whether to call it.
    """
    category: Annotated[Category | None, Field(title='Category')] = 'http_api'
    """
    Tool category. Must match definition.type.
    """
    icon: Annotated[Icon | None, Field(title='Icon', validate_default=True)] = 'globe'
    """
    Lucide icon identifier.
    """
    icon_color: Annotated[
        IconColor | None, Field(title='Icon Color', validate_default=True)
    ] = '#3B82F6'
    """
    Hex color for the tool icon.
    """
    definition: Annotated[
        HttpApiToolDefinition
        | EndCallToolDefinition
        | TransferCallToolDefinition
        | CalculatorToolDefinition
        | RateTableToolDefinition
        | McpToolDefinition
        | GoogleCalendarToolDefinition
        | ComposioToolDefinition
        | WebToolDefinition,
        Field(discriminator='type', title='Definition'),
    ]
    """
    Typed tool definition.
    """


class NodeSpec(BaseModel):
    """
    Single source of truth for a node type.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    display_name: Annotated[str, Field(title='Display Name')]
    description: Annotated[str, Field(min_length=1, title='Description')]
    """
    Human-facing explanation shown in AddNodePanel.
    """
    llm_hint: Annotated[str | None, Field(title='Llm Hint')] = None
    """
    LLM-only guidance; omitted from the UI.
    """
    docs_url: Annotated[str | None, Field(title='Docs Url')] = None
    """
    Documentation URL shown in the node editor.
    """
    category: NodeCategory
    icon: Annotated[str, Field(title='Icon')]
    version: Annotated[str | None, Field(title='Version')] = '1.0.0'
    properties: Annotated[list[PropertySpec], Field(title='Properties')]
    examples: Annotated[list[NodeExample] | None, Field(title='Examples')] = None
    graph_constraints: GraphConstraints | None = None


class NodeTypesResponse(BaseModel):
    spec_version: Annotated[str, Field(title='Spec Version')]
    node_types: Annotated[list[NodeSpec], Field(title='Node Types')]


class UpdateWorkflowRequest(BaseModel):
    name: Annotated[str | None, Field(title='Name')] = None
    workflow_definition: Annotated[
        dict[str, Any] | None, Field(title='Workflow Definition')
    ] = None
    template_context_variables: Annotated[
        dict[str, Any] | None, Field(title='Template Context Variables')
    ] = None
    workflow_configurations: WorkflowConfigurationDefaults | None = None


PropertySpec.model_rebuild()
