"""What the human hears in the half-second before the caller is handed to them.

A transfer that says *"you have answered a transfer call"* is a cold transfer
with extra steps. The person who picks up knows nothing: not who is on the
line, not what they have already explained, not what they want. So they ask
again, and the caller — who has just spent three minutes explaining it — repeats
themselves to a second party. That is the moment people decide a voice agent
made things worse.

A **briefing** is a short line played into the destination's leg only, before
the caller is bridged in. The caller never hears it. The mechanism has been
here all along: every provider dials the destination into a conference and
speaks to it on answer, and that speech was a hardcoded sentence.

Two decisions worth stating.

**It is composed from what was extracted, not generated by a model.** Retell
generates a summary at transfer time. That is a language-model call on the
critical path, with the caller on hold and a human holding a ringing handset,
and it buys a paraphrase of variables we already captured exactly. A template
over `gathered_context` is instant, deterministic, and cannot hallucinate a
symptom or an amount into a briefing that a person will then act on.

**It is capped, hard.** A whisper is spoken while the caller waits in silence
and the human waits to be connected. Anything past a couple of sentences and
the human has stopped listening and the caller thinks the line has dropped.
"""

from __future__ import annotations

from typing import Any

from loguru import logger

from api.utils.template_renderer import render_template

#: Spoken aloud at roughly three words a second, so this is about twelve
#: seconds. Past that the human stops listening and the caller, sitting in
#: silence, starts saying "hello?".
MAX_BRIEFING_CHARS = 240

#: What a destination hears when nothing is configured. Deliberately still
#: better than nothing — it says a transfer is happening and that a person is
#: waiting, which is the minimum a human needs to answer correctly.
DEFAULT_BRIEFING = "Transferring a caller to you now. Please hold."


def _truncate(text: str) -> str:
    """Cut at a sentence if there is one to cut at, mid-word only as a last resort."""
    if len(text) <= MAX_BRIEFING_CHARS:
        return text
    window = text[:MAX_BRIEFING_CHARS]
    for stop in (". ", "! ", "? "):
        cut = window.rfind(stop)
        if cut > MAX_BRIEFING_CHARS // 2:
            return window[: cut + 1].strip()
    return window.rsplit(" ", 1)[0].strip()


def build_briefing(
    *,
    template: str | None,
    initial_context: dict[str, Any] | None = None,
    gathered_context: dict[str, Any] | None = None,
) -> str:
    """The line spoken to the human who answers, or the default when there is none.

    ``template`` is the operator's, with ``{{variables}}`` resolved against the
    call the same way a webhook payload is. An unresolvable variable renders
    empty rather than as literal braces — a human hearing "the caller's issue
    is curly curly issue curly curly" is worse than one hearing a gap.
    """
    if not template or not template.strip():
        return DEFAULT_BRIEFING

    initial = dict(initial_context or {})
    context = {
        **initial,
        "initial_context": initial,
        "gathered_context": dict(gathered_context or {}),
    }

    try:
        rendered = render_template(template, context)
    except Exception as exc:
        # A briefing that fails to render must not fail the transfer. The
        # caller is already on hold and the destination is already ringing;
        # a generic line is a far better outcome than an exception here.
        logger.warning(f"Transfer briefing failed to render, using default: {exc}")
        return DEFAULT_BRIEFING

    text = " ".join(str(rendered or "").split())
    return _truncate(text) if text else DEFAULT_BRIEFING


def briefing_from_config(
    config: dict[str, Any],
    *,
    initial_context: dict[str, Any] | None = None,
    gathered_context: dict[str, Any] | None = None,
) -> str:
    """Read the briefing template off a transfer tool's config and build it."""
    template = config.get("briefing") or config.get("briefing_template")
    return build_briefing(
        template=template if isinstance(template, str) else None,
        initial_context=initial_context,
        gathered_context=gathered_context,
    )
